package io.panther.demo;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.View;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import io.panther.Panther;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void onClick(View v) {
        if (v.getId() == R.id.btnMain) {
            List<StudentBean> studentList = new ArrayList<>();
            StudentBean student = new StudentBean();
            student.setId(1000001L);
            student.setGender(1);
            student.setName("Stephen Curry");
            student.setBirthday(new Date(420457396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000002L);
            student.setGender(1);
            student.setName("LeBron James");
            student.setBirthday(new Date(420357396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000003L);
            student.setGender(0);
            student.setName("Lily Zhang");
            student.setBirthday(new Date(420157396000L));
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);
            student = new StudentBean();
            student.setId(1000004L);
            student.setGender(null);
            student.setName("Qi Zhou");
            student.setBirthday(null);
            studentList.add(student);

            long start = System.currentTimeMillis();
            Panther.get(this).writeInDatabase("students", studentList);
            Log.i("panther", "write cost: " + (System.currentTimeMillis() - start) + " ms");

            long start1 = System.currentTimeMillis();
            List<StudentBean> studentList1 = (List<StudentBean>) Panther.get(this).readObjectFromDatabase("students", StudentBean.class);
            Log.i("panther", "read cost: " + (System.currentTimeMillis() - start1) + " ms");
//            for (StudentBean s : studentList1) {
//                Log.i("stu", s.toString());
//            }
//
//            Panther.get(this).writeInMemory("students", studentList, true);
//
//            List<StudentBean> studentList2 = (List<StudentBean>) Panther.get(this).readFromMemory("students", true);
//            for (StudentBean s : studentList2) {
//                Log.i("stu2", s.toString());
//            }
        }
    }
}